2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Configure stats pid to 15310
2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Loading settings from /home2/kyrylo/.config/wandb/settings
2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Loading settings from /home2/kyrylo/Play/SMAI-Project/LSTM-Pruning/code/wandb/settings
2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code/lstmModel.py', 'program': 'lstmModel.py'}
2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-11-03 22:56:01,234 INFO    MainThread:15310 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-11-03 22:56:01,235 INFO    MainThread:15310 [wandb_init.py:_log_setup():524] Logging user logs to /home2/kyrylo/Play/SMAI-Project/LSTM-Pruning/code/wandb/run-20231103_225601-nf0rkwr7/logs/debug.log
2023-11-03 22:56:01,235 INFO    MainThread:15310 [wandb_init.py:_log_setup():525] Logging internal logs to /home2/kyrylo/Play/SMAI-Project/LSTM-Pruning/code/wandb/run-20231103_225601-nf0rkwr7/logs/debug-internal.log
2023-11-03 22:56:01,235 INFO    MainThread:15310 [wandb_init.py:init():564] calling init triggers
2023-11-03 22:56:01,235 INFO    MainThread:15310 [wandb_init.py:init():572] wandb.init called with sweep_config: {}
config: {}
2023-11-03 22:56:01,235 INFO    MainThread:15310 [wandb_init.py:init():614] starting backend
2023-11-03 22:56:01,235 INFO    MainThread:15310 [wandb_init.py:init():618] setting up manager
2023-11-03 22:56:01,238 INFO    MainThread:15310 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-11-03 22:56:01,241 INFO    MainThread:15310 [wandb_init.py:init():624] backend started and connected
2023-11-03 22:56:01,247 INFO    MainThread:15310 [wandb_init.py:init():715] updated telemetry
2023-11-03 22:56:01,302 INFO    MainThread:15310 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-11-03 22:56:02,073 INFO    MainThread:15310 [wandb_run.py:_on_init():2220] communicating current version
2023-11-03 22:56:02,382 INFO    MainThread:15310 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-11-03 22:56:02,382 INFO    MainThread:15310 [wandb_init.py:init():799] starting run threads in backend
2023-11-03 22:56:03,452 INFO    MainThread:15310 [wandb_run.py:_console_start():2199] atexit reg
2023-11-03 22:56:03,453 INFO    MainThread:15310 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-11-03 22:56:03,455 INFO    MainThread:15310 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-11-03 22:56:03,455 INFO    MainThread:15310 [wandb_run.py:_redirect():2144] Redirects installed.
2023-11-03 22:56:03,458 INFO    MainThread:15310 [wandb_init.py:init():840] run started, returning control to user process
2023-11-03 22:56:03,459 INFO    MainThread:15310 [wandb_config.py:__setitem__():151] config set beam_size = 5 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x1458c40b72b0>>
2023-11-03 22:56:03,459 INFO    MainThread:15310 [wandb_run.py:_config_callback():1324] config_cb beam_size 5 None
2023-11-03 22:56:03,459 INFO    MainThread:15310 [wandb_config.py:__setitem__():151] config set max_decoding_time_step = 100 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x1458c40b72b0>>
2023-11-03 22:56:03,459 INFO    MainThread:15310 [wandb_run.py:_config_callback():1324] config_cb max_decoding_time_step 100 None
2023-11-03 22:59:00,148 WARNING MsgRouterThr:15310 [router.py:message_loop():77] message_loop has been closed
